# Utiliser une image officielle Python
FROM python:3.11-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers
COPY . .

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Lancer l'API
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "4850"]
